apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-alb
  namespace: bookstore-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: internal-alb
  template:
    metadata:
      labels:
        app: internal-alb
    spec:
      containers:
        - name: internal-alb
          image: nginx:1.27-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /status
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /status
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: internal-alb-nginx-config
