apiVersion: v1
kind: Service
metadata:
  name: internal-alb
  namespace: bookstore-ns
spec:
  selector:
    app: internal-alb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
