FROM ubuntu:22.04

WORKDIR /app

RUN apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY deployment/binaries/customer/bookstore_customers /usr/local/bin/bookstore_customers
RUN chmod +x /usr/local/bin/bookstore_customers

ENV BIND_ADDRESS=0.0.0.0:3000

EXPOSE 3000

CMD ["/usr/local/bin/bookstore_customers"]
