apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-customers
  namespace: bookstore-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookstore-customers
  template:
    metadata:
      labels:
        app: bookstore-customers
    spec:
      containers:
        - name: bookstore-customers
          image: karanshah0206/bookstore-customers:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: BIND_ADDRESS
              value: "0.0.0.0:3000"
            - name: DATABASE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: bookstore-db-endpoints
                  key: aurora_writer_endpoint
            - name: DATABASE_USERNAME
              value: "root"
            - name: DATABASE_PASSWORD
              value: "rootroot"
            - name: DATABASE_NAME
              value: "bookstore"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "98.88.99.206:9092,34.195.107.7:9092,54.221.160.63:9092"
          livenessProbe:
            httpGet:
              path: /status
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
