FROM ubuntu:22.04

WORKDIR /app

RUN apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY deployment/binaries/crm/customer_crm /usr/local/bin/customer_crm
RUN chmod +x /usr/local/bin/customer_crm

CMD ["/usr/local/bin/customer_crm"]
