apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-books
  namespace: bookstore-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-books
  template:
    metadata:
      labels:
        app: bookstore-books
    spec:
      containers:
        - name: bookstore-books
          image: karanshah0206/bookstore-book:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: BIND_ADDRESS
              value: "0.0.0.0:3000"
            - name: DATABASE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: bookstore-db-endpoints
                  key: aurora_writer_endpoint
            - name: DATABASE_USERNAME
              value: "root"
            - name: DATABASE_PASSWORD
              value: "rootroot"
            - name: DATABASE_NAME
              value: "bookstore"
            - name: RECOMMENDATION_ENDPOINT
              value: "http://34.195.107.7"
            - name: GEMINI_API_KEY
              value: "replace-with-gemini-api-key"
          livenessProbe:
            httpGet:
              path: /status
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
