apiVersion: v1
kind: Service
metadata:
  name: bookstore-books
  namespace: bookstore-ns
spec:
  selector:
    app: bookstore-books
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
