apiVersion: v1
kind: Service
metadata:
  name: bookstore-web-bff
  namespace: bookstore-ns
spec:
  selector:
    app: bookstore-web-bff
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
